### PR TITLE
Sync changes from UX481FA fork with ACPI audit

### LINKED ISSUE #4: Investigate 'Garbled ScreenPad Plus screen'
Follow up to https://github.com/shiecldk/ASUS-ZenBook-Pro-Duo-15-OLED-UX582-Hackintosh/issues/2 investigating scrambled screenpad plus display-out with fully-detected display. Tracking progress [here](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/milestone/1).

### LINKED ISSUE #6: Screenpad Plus Backlight Control
Backlight is set by ACPI calls exposed through a windows proprietary WMI (an interface for making those calls). For reference, there is a linux module (for the zenbook duo) that probes ACPI for methods controlling backlight of the screenpad. Below details basic methods for the display's backlight control implemented similarly to keyboard backlight control in [AsusSMC](https://github.com/hieplpvip/AsusSMC):
https://github.com/Plippo/asus-wmi-screenpad/blob/master/asus-wmi.h#L50-L74
https://github.com/Plippo/asus-wmi-screenpad/blob/master/asus-wmi.c#L819-L831

Mapping Screenpad backlight brightness in a control center slider like keyboard brightness may also be a better UX implementation:

image

### LINKED ISSUE #8: [VoodooI2CHID] Fixing Physical Buttons on Trackpad
So, after updating Kexts... the trackpad works!

CONNEXION : #4 #3

### LINKED ISSUE #12: Fix VoodooI2CHID issue w/ Touchscreen
On startup, touchscreen on both displays works in legacy mouse mode (no multitouch/PTP mode); it also appears to no longer respond about a minute after login. These issues were also described in @shiecldk's [tonymacx86 UX582 thread](https://www.tonymacx86.com/threads/voodooi2c-help-and-support.243378/page-144) prior to resolution, and describes an issue with VoodooI2CHID where changing driver/device priority can break multitouch.

@gkvt's fork of VoodooI2C at https://github.com/gvkt/VoodooI2CHID resolves an architecture incompatibility w/ multi-I2C HID devices; the workaround allows for greater control of which driver is attached to which device. The pull request for this fork was tracked in https://github.com/VoodooI2C/VoodooI2CHID/pull/58 (closed) and https://github.com/VoodooI2C/VoodooI2CHID/pull/59 (merged).

Refer to https://github.com/VoodooI2C/VoodooI2C/issues/485#issuecomment-968115898 for Info.plist changes (changes are to match drivers to device-specific product ids rather than device names).

For reference, [discussion on multi-touch support for touchscreen w/ VoodooI2C](https://github.com/VoodooI2C/VoodooI2C/issues/474#issuecomment-979154995) details the debugging used to modify the kext's Info.plist to prevent interference from touchscreen/precision trackpad event drivers.

### PR DESCRIPTION
**Pull request by Qonfused**
### Current tasks:
- **Screenpad Plus**
    - [x] Fix backlight control (see https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/issues/6#issuecomment-1336570223)
- **Keyboard**
    - [x] Add missing ATKD functions
            - Backlight
        - [x] Bind FN + Lock backlight to `_QD5` EC event.
        - [x] Add keyboard backlight control (bound to `_Q32` or 'toggle screenpad' key).
        - [x] Add Screenpad 5-mode backlight control (bound to` _Q31` or 'switch displays' key).
    - [x] Investigate custom keyboard scan map w/ PS2 button overrides
- **Misc. Interface Devices** (I2C: Trackpad, Touchscreen; PS2: Keyboard, Mouse Buttons)
    - [x] Resolve Trackpad APIC/GPIO pinning issue (see https://github.com/VoodooI2C/VoodooI2C/issues/171, https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/issues/12#issuecomment-1352642851)

### Housekeeping:
- **ACPI**
    - [x] Preserve atomic ACPI file structure
        - [x] Map [**`SSDT-UX481FA.aml`**](https://github.com/wern-apfel/Zenbook-UX481FA/blob/main/EFI/OC/ACPI/SSDT-UX481FA.aml) to essential SSDTs:
            - [x] **`SSDT-AWAK.aml`**
            - [x] **`SSDT-EC-USBX.aml`**
                - [x] SSDT-EC
                - [x] ~~SSDT-USBX~~ (handled by SSDT-USB)
            - [x] **`SSDT-PLUG.aml`** (required for macOS <12.3)
            - [x] **`SSDT-PNLF.aml`**
            - [x] **`SSDT-GPIO.aml`** or **`SSDT-XOSI.aml`**
                - [x] GPIO Device
                - [x] Trackpad GPIO fix
        - [x] Investigate ACPI imports (e.g. importing macOS overrides for WAK function)
    - [x] Investigate any sound card IRQ conflicts (HPET).
    - [x] Fix SSDT-DISABLE-GPU null check and dependency
- **Kexts**
    - [x] Verify kext load order (w/ plugins)
    - [x] Verify misc. kexts are still warranted:
        - [x] [**`CpuTscSync.kext`**](https://github.com/acidanthera/CpuTscSync) — fixes kernel panics on wake
        - [x] [**`DiskArbitrationFixup.kext`**](https://github.com/Goldfish64/DiskArbitrationFixup) — userspace; hides unreadable disk message on boot
        - [x] [**`ECEnabler.kext`**](https://github.com/1Revenger1/ECEnabler) — addresses EC read byte length
        - [x] [**`HibernationFixup.kext`**](https://github.com/acidanthera/HibernationFixup) — resolves hibernation issues w/ RTC + NVRAM
- **OpenCore**
    - [x] Add Wi-Fi + Bluetooth kexts for different macOS targets (Catalina, Big Sur)

### CODE REVIEW

**Comment by Qonfused** [comment]
Will defer users to use the [USBToolbox](https://github.com/USBToolBox/tool) method instead of relying on an ACPI patch for mapping USB personalities. USBX can be merged with the EC device as SSDT-EC/USBX for consistency with the [Dortania OpenCore guide](https://dortania.github.io/Getting-Started-With-ACPI/Universal/ec-fix.html).

**Comment by Qonfused** [comment]
Missing GPIO device from SSDT-UX481FA. Will merge w/ GPIO pinning the trackpad to resolve GPIO.

**Comment by Qonfused** [comment]
Will test for any regressions before implementing further fixes.

**Comment by Qonfused** [comment]
TODO:
- [ ] Add missing ATKD functions (e.g. FN Lock)
- [ ] Add missing internal USB personalities (DCAM/DCAN, etc)
- [ ] Investigate custom keyboard scan map

**Comment by Qonfused** [comment]
As the GPIO device already exists, investigating the XOSI fix w/ pinning the trackpad should resolve GPI0. Some pre-requisite work has already been done for GPI0 pinning the trackpad, though the trackpad is still reported operating in polling mode (ETPD device).

**Comment by Qonfused** [comment]
Update: GPI0 may need to be resolved in a separate issue, as the GPI0 pin calculated from the CoffeeLake-LF table does not appear to work (no ETPD device in IOReg).

**Comment by Qonfused** [comment]
Update: GPI0 may need to be resolved in a separate issue, as the GPI0 pin calculated from the CoffeeLake-LF table does not appear to work.

**Comment by Qonfused** [comment]
Will test if GPIO pinning I2C touchscreen devices resolves intermittency issue (caused from polling interrupt collision).

**Comment by Qonfused** [comment]
@UsedDiscord Does touchscreen on the screenpad plus work with the last commit ([zip URL](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/archive/refs/heads/UX481FA-parity.zip))? It should move the cursor on the primary display (known issue), but for me it is not working when GPIO pinned.

You may need to run these two commands to check if GPIO is working and what Voodoo drivers are attaching:
```sh
ioreg -rxn TPL1 -k i2cAddress -d1 | grep -i "gpio"
```

```sh
ioreg -rxn IOHIDInterface -k "VoodooI2CServices Supported" -t | grep -E 'IOACPIPlatformDevice|IOPCIDevice|VoodooI2CDeviceNub|VendorID|ProductID|HIDEventDriver  <class VoodooI2C|Interface  <class VoodooI2C' | cut -d "<" -f1
```

**Comment by UsedDiscord** [comment]
> @UsedDiscord Does touchscreen on the screenpad plus work with the last commit ([zip URL](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/archive/refs/heads/UX481FA-parity.zip))? It should move the cursor on the primary display (known issue), but for me it is not working when GPIO pinned.
> 
> You may need to run these two commands to check if GPIO is working and what Voodoo drivers are attaching:
> 
> ```shell
> ioreg -rxn TPL1 -k i2cAddress -d1 | grep -i "gpio"
> ```
> 
> ```shell
> ioreg -rxn IOHIDInterface -k "VoodooI2CServices Supported" -t | grep -E 'IOACPIPlatformDevice|IOPCIDevice|VoodooI2CDeviceNub|VendorID|ProductID|HIDEventDriver  <class VoodooI2C|Interface  <class VoodooI2C' | cut -d "<" -f1
> ```

@Qonfused 
I haven't tested your latest Commit yet, I was busy with my law classes, I just did the EDID dump in a hurry before leaving... with an old commit (yeah I screwed up my own EFI so I downloaded yours directly..)

I will test your EFI tomorrow with the last Commit
I'll be happy to give you an update tomorrow.

**Comment by Qonfused** [comment]
No worries there! Just want to verify it's an actual issue and not something specific to my install. The ZIP archive for that commit is available [here](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/archive/08c21be6bd6056c278924dc1da04147b614b62a8.zip). I'll go ahead and revert the screenpad GPIO pinning in another commit for now.

**Comment by UsedDiscord** [comment]
> No worries there! Just want to verify it's an actual issue and not something specific to my install. The ZIP archive for that commit is available [here](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/archive/08c21be6bd6056c278924dc1da04147b614b62a8.zip). I'll go ahead and revert the screenpad GPIO pinning in another commit for now.

Thanks for your patience! I'm trying to work on the EDID problem myself :), so if you're interested, I'm working on it.

But yep, I'll test it tomorrow, it's always a joy to read you @Qonfused  :) and to work on this macOS x)

**Comment by Qonfused** [comment]
It seems that the GPIO pin I had used didn't work (followed the same method for both touch screens as I detailed for the trackpad in https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/pull/19#issuecomment-1369108835), but it does work using `0x55` instead. You can try using the first archive link which pulls from the latest commit instead.

**Comment by UsedDiscord** [comment]
Nice that, good work :) I'll keep a feedback tomorrow to do a test on my side :)

**Comment by Qonfused** [comment]
Seems adding a [MSOS fix](https://github.com/5T33Z0/OC-Little-Translated/tree/main/05_Laptop-specific_Patches/Brand-specific_Patches/ASUS_Special_Patch) will allow for brightness keys to work without SSDT-ATKD.

Here are the original EC methods for brightness keys, dependent on MSOS returning Windows 8 or higher:

```dsl
Method (_Q0E, 0, NotSerialized)  // _Qxx: EC Query, xx=0x00-0xFF
{
    If ((MSOS () >= OSW8))
    {
        BRTN (0x87)
    }

    Return (Zero)
}

Method (_Q0F, 0, NotSerialized)  // _Qxx: EC Query, xx=0x00-0xFF
{
    If ((MSOS () >= OSW8))
    {
        BRTN (0x86)
    }

    Return (Zero)
}
```

**Comment by UsedDiscord** [comment]
so, good morning @Qonfused , I took your last commit https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/commit/07eafd3745779650f1e3cd2c15c688a0a4e20320.

Several points I note: 

1) The touchpad of the screenpad worked some time before a standby (without doing it on purpose of the PC...) and it didn't work after... smh...
same for the main touch screen...

2) I have done your orders, here are the pictures:

image

Command : ```ioreg -rxn TPL1 -k i2cAddress -d1 | grep -i "gpio"```
Result : 
```
magik@LAPTOP-58F616EU ~ % ioreg -rxn TPL1 -k i2cAddress -d1 | grep -i "gpio"
      "gpioIRQ" = 0x8
      "Interrupt Mode" = "GPIO"
      "gpioPin" = 0x56
```
-------------------------------------------

image

Command : ```ioreg -rxn IOHIDInterface -k "VoodooI2CServices Supported" -t | grep -E 'IOACPIPlatformDevice|IOPCIDevice|VoodooI2CDeviceNub|VendorID|ProductID|HIDEventDriver  <class VoodooI2C|Interface  <class VoodooI2C' | cut -d "<" -f1```
Result : 
```
magik@LAPTOP-58F616EU ~ % ioreg -rxn IOHIDInterface -k "VoodooI2CServices Supported" -t | grep -E 'IOACPIPlatformDevice|IOPCIDevice|VoodooI2CDeviceNub|VendorID|ProductID|HIDEventDriver  <class VoodooI2C|Interface  <class VoodooI2C' | cut -d "<" -f1
      +-o PCI0@0  
          +-o I2C0@15  
                  +-o TPL1  
                        |   "VendorID" = 0x4f3
                        |   "ProductID" = 0x2b6a
                        +-o VoodooI2CTouchscreenHIDEventDriver  
                          +-o VoodooI2CMultitouchInterface  
      +-o PCI0@0  
          +-o I2C1@15,1  
                  +-o ETPD  
                        |   "VendorID" = 0x4f3
                        |   "ProductID" = 0x310e
                        +-o VoodooI2CPrecisionTouchpadHIDEventDriver  
                          +-o VoodooI2CMultitouchInterface  
      +-o PCI0@0  
          +-o I2C3@15,3  
                  +-o TPL0  
                        |   "VendorID" = 0x4f3
                        |   "ProductID" = 0x2c58
                        +-o VoodooI2CTouchscreenHIDEventDriver  
                          +-o VoodooI2CMultitouchInterface  
magik@LAPTOP-58F616EU ~ % 
```

3) my trackpad jumps a lot less than before anyway! 

4) the Disable Screenpad function (or darken it, second last button... the one on the left of the Power button) works, the main screen becomes black for a few seconds but nothing more :)

5) the function to switch the Screenpad with the main screen does not switch the 2 screens but allows to put + or - brightness on the Screenpad

6) FN+F11 : "Clear" all windows, and if you click on them, they come back

7) F7 (Only F7) allows to decrease or increase the keyboard brightness

8) F6 (Only F6) allows you to disable or enable the trackpad

9) F4 and F5 (only F4 and F5) allows to increase or decrease the brightness of the main screen

10) F1,F2,F3 (Only F1,F2,F3) allows to decrease the sound, to cut it or to increase it, unfortunately, I lose the audio a few seconds after the starting...


Wishing you a pleasant day :)
- @UsedDiscord

**Comment by Qonfused** [comment]
It seems that VoodooI2C may still be polling a device somewhere, though the trackpad + both touchscreen are GPIO pinned. There is also a HID device for stylus input, which I may also need to address to resolve that.

The FN lock key is only cosmetic at the moment - it just toggles the keyboard light for it.

**Comment by UsedDiscord** [comment]
after, I put back like that just by removing an ACPI the Disable GPU which is useless to me and which causes me errors in addition in the logs...

I didn't read the logs of the Kernel, nor of VoodooI2C... I just did a quick test, I have some exams in a few days... It's not easy to finish my courses and to do the test on a trackpad that doesn't work haha...

**Comment by Qonfused** [comment]
> after, I put back like that just by removing an ACPI the Disable GPU which is useless to me and which causes me errors in addition in the logs... ((I don't have Nvidia in my pc)

This issue was overlooked. I'll add a null check to skip applying the DGPU SSDT on the UX481FA model.

**Comment by Qonfused** [comment]
Added a proper disable method with S3 fallback with the proper null checks, so it should always work or early return in the case of UX481FL or UX481FA models. You can check for any ACPI errors by running `log show --last boot | grep AppleACPIPlatform`.

**Comment by UsedDiscord** [comment]
Thank, I'll see when I work at night :) but it will save a few MICRO seconds in the MacOS boot since it doesn't have to check this... In that's great

(Micro seconds : in its pure state, it is really 0,00001 and still...)

**Comment by Qonfused** [comment]
Will resolve these issues in separate PRs
- **Screenpad Plus**
    - [ ] Resolve display EDID issue (see https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/issues/4#issuecomment-1327859276)
    - [x] Investigate LPC bus / eSPI interface (see https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/issues/4#issuecomment-1365869534)
- **Misc. Interface Devices** (I2C: Trackpad, Touchscreen; PS2: Keyboard, Mouse Buttons)
    - [ ] Resolve Mouse button issue (see https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/issues/8#issuecomment-1356333102)
    - [ ] Resolve I2C polling intermittency issue (see https://github.com/VoodooI2C/VoodooI2C/issues/321)

**Comment by Qonfused** [comment]
Camera requires info.plist changes for all instances of `idProduct` and `idVendor` with decimal form of the product and vendor ids. You can find these values for the webcam in system information under USB. May require documentation for potential fixes.

In my case I had `0x56cb` and `0x13d3` for my product and vendor ids, which convert to 22219 and 5075:  [AnyiSightCam.kext.zip](https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/files/10338165/AnyiSightCam.kext.zip).

**Comment by Qonfused** [comment]
Unclear what ADB codes these keys are being mapped to.
```dsl
/*
 * Remaps keyboard based on scan codes.
 *
 * Refer to the header file ApplePS2ToADBMap.h for common scan codes:
 * https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller/blob/master/VoodooPS2Keyboard/ApplePS2ToADBMap.h
 */
DefinitionBlock ("", "SSDT", 2, "UX434", "PS2KBD", 0x00000000)
{
    External (_SB_.PCI0.LPCB.PS2K, DeviceObj)

    Scope (_SB.PCI0.LPCB.PS2K)
    {
        Name (RMCF, Package (0x02)
        {
            "Keyboard", 
            Package (0x06)
            {
                "Custom PS2 Map", 
                Package (0x06)
                {
                    Package (0x00){},
                    "46=80",   // 0x006b=0x0050, Scroll Lock
                    "e045=80", // 0x0071=0x0050, Pause
                    "e037=64", // 0x0000=0x0040, Print Screen
                    "e052=67", // 0x0000=0x0043, Insert
                    "e05d=57"  // 0x0a00=0x0038, App (context menu key)
                },

                "MaximumMacroTime",
                0x017D7840, 
                "Macro Inversion",
                Package (0x03)
                {
                    Package (0x00){}, 
                    Buffer (0x0C)
                    {
                        /* 0000 */  0xFF, 0xFF, 0x01, 0x57, 0x00, 0x00, 0x00, 0x00,
                        /* 0008 */  0x02, 0x5B, 0x01, 0x19
                    },

                    Buffer (0x0C)
                    {
                        /* 0000 */  0xFF, 0xFF, 0x01, 0xD7, 0x00, 0x00, 0x00, 0x00,
                        /* 0008 */  0x01, 0x99, 0x02, 0xDB
                    }
                }
            }
        })
    }
}
```

**Comment by Qonfused** [comment]
Will resolve these issues in separate PRs
- **Screenpad Plus**
    - [ ] Resolve display EDID issue (see https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/issues/4#issuecomment-1327859276)
    - [x] Investigate LPC bus / eSPI interface (see https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/issues/4#issuecomment-1365869534)
- **Misc. Interface Devices** (I2C: Trackpad, Touchscreen; PS2: Keyboard, Mouse Buttons)
    - [ ] Resolve Mouse button issue (see https://github.com/Qonfused/ASUS-ZenBook-Duo-14-UX481-Hackintosh/issues/8#issuecomment-1356333102)
    - [ ] Resolve I2C intermittency issue (see https://github.com/VoodooI2C/VoodooI2C/issues/321)
- **Peripherals**
    - [x] Investigate internal USB personalities (DCAM/DCAN, etc)
    - [ ] Resolve built-in microphone issue (requires AppleHDA patch)
    - [ ] Investigate built-in camera issue (potential device enable issue)

**Comment by Qonfused** [comment]
Still need to test on different macOS versions (Catalina, Big Sur, Monterey <12.3) before merge.

**Comment by Qonfused** [comment]
TODO (for Catalina and Big Sur):
- [ ] Address APFS min version
- [ ] Address secure boot

**Pull request merged**
